<template>
  <article class="max-w-3xl mx-auto px-4 py-10 prose prose-gray">
    <BreadCrumb />
    <h1>Terms of Service</h1>
    <p class="text-sm text-gray-500">{{ $t('legal.lastUpdated') }}: September 30, 2026</p>

    <p>
      These Terms of Service (&quot;Terms&quot;) govern your use of the Toolcairn website and its
      tools, available at <a href="https://toolcairn.com/">toolcairn.com</a>. By accessing or using
      Toolcairn, you agree to these Terms. If you do not agree, please do not use the service.
    </p>

    <h2>1. The service</h2>
    <p>
      Toolcairn provides free, browser-based tools for tasks such as compressing PDFs, resizing
      images, generating QR codes, and formatting JSON. We do not require an account or a
      subscription. Tools and features may change, be added, or be removed at any time.
    </p>

    <h2>2. Acceptable use</h2>
    <ul>
      <li>You agree not to use Toolcairn for any unlawful purpose or in a way that could damage or impair the service.</li>
      <li>You may not attempt to access, scrape, or overload the infrastructure that runs the service.</li>
      <li>You are responsible for the content you submit or process using our tools.</li>
    </ul>

    <h2>3. No warranty</h2>
    <p>
      The service is provided &quot;as is&quot; and &quot;as available&quot;, without warranties of
      any kind, express or implied, including but not limited to warranties of merchantability,
      fitness for a particular purpose, or accuracy. Conversions, compression, and other output may
      not be perfect for every file, and you are responsible for verifying results.
    </p>

    <h2>4. Limitation of liability</h2>
    <p>
      To the maximum extent permitted by law, Toolcairn and its operators shall not be liable for
      any indirect, incidental, special, consequential, or punitive damages, or for any loss of
      data or profits, arising from your use of the service, even if advised of the possibility of
      such damages.
    </p>

    <h2>5. Intellectual property</h2>
    <p>
      The Toolcairn name, logo, design, and original content are owned by Toolcairn. You may not
      copy, reproduce, or redistribute them for commercial purposes without our written consent.
      The output generated by the tools belongs to you, and you are solely responsible for how you
      use it.
    </p>

    <h2>6. Third-party services and advertising</h2>
    <p>
      Toolcairn displays advertising served by third parties, including Google AdSense. We are not
      responsible for the content, policies, or practices of third-party advertisers or websites.
      Google&apos;s advertising cookies are governed by its own privacy policy and by our
      <NuxtLink to="/privacy">Privacy Policy</NuxtLink>.
    </p>

    <h2>7. Termination</h2>
    <p>
      We may suspend or terminate access to all or part of the service at any time, with or without
      notice, if we believe these Terms have been violated or to protect the service.
    </p>

    <h2>8. Changes to these Terms</h2>
    <p>
      We may revise these Terms at any time. The revised Terms will be posted on this page with an
      updated date. Continued use of the service after changes means you accept the new Terms.
    </p>

    <h2>9. Governing law</h2>
    <p>
      These Terms are governed by the laws of [Your Jurisdiction], without regard to conflict of
      law principles. [Note: replace with your country/state of registration before publishing.]
    </p>

    <h2>10. Contact</h2>
    <p>
      Questions about these Terms?
      <a href="mailto:hello@toolcairn.com">hello@toolcairn.com</a> or
      <NuxtLink to="/contact">contact us</NuxtLink>.
    </p>
  </article>
</template>

<script setup lang="ts">
const route = useRoute()

useSeoMeta({
  title: 'Terms of Service',
  description: 'The terms that govern your use of Toolcairn — free online tools. Read about acceptable use, warranties, liability, and more.',
  ogTitle: 'Terms of Service — Toolcairn',
  ogDescription: 'The terms that govern your use of Toolcairn — free online tools.',
  ogUrl: `https://toolcairn.com${route.path}`,
  ogType: 'website',
})

useHead({
  link: [{ rel: 'canonical', href: 'https://toolcairn.com/terms' }],
})
</script>